[dev]
    command = "npm run serve"
    functions ="dist"

[build]
    functions = "dist"


[[headers]]
    for = "/*"
    [headers.values]
        Access-Control-Allow-Origin= "*"
        Access-Control-Allow-Headers= "Content-Type"
        Access-Control-Allow-Methods= "GET, POST, PUT, DELETE"

